services:
  - type: web
    name: quiz-platform
    runtime: docker
    plan: free
    dockerfile: ./Dockerfile
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: false
      - key: PORT
        value: 8000
