# Generated by Django 5.2.8 on 2026-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_question_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_access_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
