# Generated by Django 5.2.8 on 2026-02-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_event_event_access_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_entries', to='accounts.event')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_entries', to='accounts.round')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
