# Generated by Django 5.2.8 on 2026-02-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_candidateentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
