# Generated by Django 5.2.8 on 2026-02-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_candidateentry_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
