# Generated by Django 5.2.8 on 2026-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_round_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
    ]
