# Generated by Django 5.2.8 on 2026-02-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_candidateentry_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
