# Generated by Django 5.2.8 on 2026-02-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_candidateentry_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidateentry',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidateentry',
            name='total_questions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
