# Generated by Django 5.2.8 on 2026-02-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_candidateentry_access_code_used_alter_candidateentry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_hosting',
            field=models.BooleanField(default=False),
        ),
    ]
