# Generated by Django 5.2.8 on 2026-02-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_round_is_hosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateentry',
            name='access_code_used',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidateentry',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='candidateentry',
            name='is_submitted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='candidateentry',
            name='is_waiting',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='candidateentry',
            index=models.Index(fields=['round', 'access_code_used'], name='accounts_ca_round_i_69d914_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateentry',
            index=models.Index(fields=['round', 'is_waiting'], name='accounts_ca_round_i_48cdf1_idx'),
        ),
    ]
