# Generated by Django 5.2.8 on 2026-02-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_candidateentry_access_code_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='has_switched_tabs',
            field=models.BooleanField(default=False),
        ),
    ]
