# Generated by Django 5.2.8 on 2026-03-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_candidateentry_has_switched_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='quiz_started_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
