# Generated by Django 5.2.8 on 2026-04-15 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_both_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('problem_statement', models.TextField()),
                ('input_format', models.TextField(blank=True, default='')),
                ('output_format', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('sample_input', models.TextField(blank=True, default='')),
                ('sample_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='accounts.round')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DubbingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('go', 'Go'), ('rust', 'Rust'), ('kotlin', 'Kotlin'), ('swift', 'Swift'), ('ruby', 'Ruby'), ('php', 'PHP'), ('sql', 'SQL'), ('other', 'Other')], default='python', max_length=50)),
                ('code_snippet', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dubbing_questions', to='accounts.round')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
