# Generated by Django 5.2.8 on 2026-04-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_codingquestion_dubbingquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dubbingquestion',
            name='language',
            field=models.CharField(choices=[('c', 'C'), ('python', 'Python'), ('java', 'Java')], default='python', max_length=50),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='accounts.codingquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
