# Generated by Django 5.2.8 on 2026-04-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_dubbingquestion_language_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubbingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('dubbing_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='accounts.dubbingquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
