# Generated by Django 5.2.8 on 2026-04-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_dubbingtestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbingquestion',
            name='sample_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dubbingquestion',
            name='sample_output',
            field=models.TextField(blank=True, default=''),
        ),
    ]
