# Generated by Django 5.2.8 on 2026-04-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_dubbingquestion_sample_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('coding', 'Coding'), ('dubbing', 'Debugging')], default='coding', max_length=10)),
                ('question_id', models.IntegerField()),
                ('question_title', models.CharField(blank=True, default='', max_length=500)),
                ('code', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='python', max_length=20)),
                ('passed_test_cases', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('output_success', models.BooleanField(default=False)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('time_limit_met', models.BooleanField(default=False)),
                ('testcase_score', models.IntegerField(default=0)),
                ('output_score', models.IntegerField(default=0)),
                ('efficiency_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='accounts.candidateentry')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('candidate', 'question_type', 'question_id')},
            },
        ),
    ]
