# Generated by Django 5.2.8 on 2026-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateentry',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
